language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "pypy3.5"

services:
    - postgresql
    - redis-server

install:
    - pip install -r requirements.txt
    - pip install .

env:
    global:
        - RDBMS_URI='postgres://postgres@localhost/travis_ci_test'

before_script:
    - psql -c 'create database travis_ci_test;' -U postgres


script:
    - pip install coveralls
    - coverage run --source='glaucoma_analytics_rest_api' setup.py test

after_success:
  - coveralls
