language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "pypy3.5"

install:
    - pip install -r requirements.txt
    - pip install .

script:
    - pip install coveralls
    - coverage run --source='glaucoma_analytics_rest_api' setup.py test

after_success:
  - coveralls
