os: linux
dist: bionic
language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"

addons:
    apt:
        packages:
            - gyp
            - apt-transport-https
            - ca-certificates
            - gnupg
            - software-properties-common
            - wget
            - libomp-dev
            - libpq-dev

services:
    - postgresql
    - redis

install:
    - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
    - sudo apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
    - sudo apt-get install -y cmake
    - pip install -r requirements.txt
    - pip install .

env:
    global:
        - RDBMS_URI='postgres://postgres@localhost/travis_ci_test'
        - TEST_MODE=true

before_script:
    - echo 'Etc/UTC' | sudo tee /etc/timezone
    - sudo dpkg-reconfigure --frontend noninteractive tzdata
    - psql -c 'create database travis_ci_test;' -U postgres
    # Create tables
    - nvm install lts/*
    - npm config set spin false
    - npm i -g npm
    - npm i -g bunyan mocha node-gyp tslint typings typescript
    - git clone https://github.com/offscale/glaucoma-risk-calculator-rest-api
    - pushd glaucoma-risk-calculator-rest-api
    - typings i
    - npm ci
    - tsc
    - npm test || true  # We don't actually care about tests passing, just tables
    - popd
    - rm -rf glaucoma-risk-calculator-rest-api

script:
    - pip install coveralls
    - coverage run --source='glaucoma_risk_calculator_analytics_rest_api' setup.py test

after_success:
    - coveralls
